"""PDF report generator used by the dashboard."""

from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle


def build_report(data):
    """Turn the current production plan into a simple printable PDF."""
    buffer = BytesIO()
    document = SimpleDocTemplate(buffer, pagesize=A4)
    styles = getSampleStyleSheet()
    kpis = data["kpis"]

    story = [
        Paragraph("FactoryMind AI Production Report", styles["Title"]),
        Spacer(1, 12),
    ]

    kpi_rows = [
        ["KPI", "Value"],
        ["Orders", kpis["total_orders"]],
        ["Operations", kpis["planned_operations"]],
        ["Efficiency", f"{kpis['efficiency']}%"],
        ["Average Utilization", f"{kpis['average_utilization']}%"],
        ["Delay Risk", f"{kpis['delay_risk']}%"],
        ["Estimated Cost", f"Rs. {kpis['estimated_cost']:,.2f}"],
    ]

    kpi_table = Table(kpi_rows)
    kpi_table.setStyle(TableStyle([
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#19304a")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("PADDING", (0, 0), (-1, -1), 7),
    ]))
    story.extend([kpi_table, Spacer(1, 15)])

    story.append(Paragraph("Machine Utilization", styles["Heading2"]))
    machine_rows = [["Machine", "Used", "Available", "Utilization"]]
    for machine in data["machine_utilization"]:
        machine_rows.append([
            machine["machine"],
            machine["used_hours"],
            machine["available_hours"],
            f"{machine['utilization']}%",
        ])

    machine_table = Table(machine_rows)
    machine_table.setStyle(TableStyle([
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("PADDING", (0, 0), (-1, -1), 6),
    ]))
    story.extend([machine_table, Spacer(1, 15)])
    story.append(Paragraph("Generated by FactoryMind AI", styles["Italic"]))

    document.build(story)
    return buffer.getvalue()
